-- CREATED BY VERTABELO (HTTP://VERTABELO.COM)
-- LAST MODIFICATION DATE: 2020-06-06 16:43:19.828

-- FOREIGN KEYS
ALTER TABLE PATIENT
    DROP CONSTRAINT PATIENT_INSURANCE;

ALTER TABLE SERVICE
    DROP CONSTRAINT SERVICE_INSURANCE;

ALTER TABLE VISIT
    DROP CONSTRAINT VISIT_DOCTOR;

ALTER TABLE VISIT
    DROP CONSTRAINT VISIT_PATIENT;

ALTER TABLE VISIT_PROCESS
    DROP CONSTRAINT VISIT_PROCESS_DIAGNOSIS;

ALTER TABLE VISIT_PROCESS
    DROP CONSTRAINT VISIT_PROCESS_SERVICE;

ALTER TABLE VISIT_PROCESS
    DROP CONSTRAINT VISIT_PROCESS_VISIT;

-- TABLES
DROP TABLE DIAGNOSIS;

DROP TABLE DOCTOR;

DROP TABLE INSURANCE;

DROP TABLE PATIENT;

DROP TABLE SERVICE;

DROP TABLE VISIT;

DROP TABLE VISIT_PROCESS;

-- END OF FILE.


