-- DQL INSTRUCTIONS THAT MEET ALL FOLLOWING REQUIREMENTS:

-- 2 SELECT STATEMENTS THAT INCLUDES AT LEAST TWO TABLES AND CONTAINS WHERE CLAUSE
--1--
--SELECT VISIT PROCESSES AND INFORMATION ABOUT PATIENTS WHO HAS GOVERNMENTAL INSURANCE AND 
--USE SERVICE UNIT PRICE GREATER THAN $100 WITH YEARLY INCOME OF THEIR DOCTORS WHO HAS PROFESSOR TITLE...
-- ALL OF THE TABLES ARE USED IN THIS QUERY...
SELECT VP.ID PROCESS_NUMBER, D.NAME DOCTOR_NAME,D.SURNAME DOCTOR_SURNAME,(D.SALARY*12)+NVL(COMM,0) DOCTOR_INCOME,
       P.NAME PATIENT_NAME,P.SURNAME PATIENT_SURNAME,I.NAME INSURANCE, S.NAME SERVICE_NAME,
       S.UNIT_PRICE*S.QUANTITY AS PRICE,DI.NAME DIAGNOSIS_NAME
FROM SERVICE S, INSURANCE I, PATIENT P, VISIT V, DOCTOR D, VISIT_PROCESS VP,DIAGNOSIS DI
WHERE S.INSURANCE_ID = I.ID AND P.INSURANCE_ID = I.ID AND V.DOCTOR_ID = D.ID AND V.PATIENT_ID = P.ID AND VP.VISIT_ID = V.ID AND VP.DIAGNOSIS_ID = DI.ID AND DI.NAME = 'COVID-19'
AND I.NAME = 'GOVERNMENT' AND D.TITLE = 'PROFESSOR' AND S.UNIT_PRICE > 100;

--2--
-- SELECT PATIENTS WHOSE NAMES ARE NOT INCLUDE 'E' AND HAVE DOCTORS WITH COMMISSION
-- OR
-- SELECT PATIENTS NOT LIVING IN ISTANBUL AND HAVE VISIT TYPE AS 'INPATIENT'
-- OR
-- SELECT MALE PATIENTS WHO HAVE PRIVATE INSURANCE AND HAVE DOCTOR WITH SALARY GREATER THAN $5000
SELECT P.NAME PATIENT_NAME,P.SURNAME PATIENT_SURNAME, P.CITY, V.TYPE VISIT_TYPE, D.COMM 
FROM PATIENT P, VISIT V, DOCTOR D
WHERE V.PATIENT_ID = P.ID AND V.DOCTOR_ID = D.ID AND P.NAME NOT LIKE '%E%' AND D.COMM IS NOT NULL
UNION
SELECT P.NAME PATIENT_NAME,P.SURNAME PATIENT_SURNAME, P.CITY, V.TYPE VISIT_TYPE, D.COMM 
FROM PATIENT P, VISIT V, DOCTOR D
WHERE V.PATIENT_ID = P.ID AND V.DOCTOR_ID = D.ID AND P.CITY NOT IN('ISTANBUL') AND V.TYPE IN('OUTPATIENT')
UNION
SELECT P.NAME PATIENT_NAME,P.SURNAME PATIENT_SURNAME, P.CITY, V.TYPE VISIT_TYPE, D.COMM 
FROM PATIENT P, VISIT V, DOCTOR D, INSURANCE I
WHERE V.PATIENT_ID = P.ID AND V.DOCTOR_ID = D.ID AND P.INSURANCE_ID = I.ID AND I.NAME IN('PRIVATE') AND D.SALARY > 5000;


-- 2 SELECT statements with aggregate functions
--1--
-- SELECT AVERAGE SALARY FOR EVERY DOCTOR TITLE 
-- WITH COUNT OF VISIT PROCESS DAIGNOSIS IS CANCER GREATER THAN 2.
SELECT D.TITLE, AVG(D.SALARY) AVERAGE_SALARY
FROM PATIENT P, VISIT V, DOCTOR D, VISIT_PROCESS VP,DIAGNOSIS DI
WHERE V.DOCTOR_ID = D.ID AND V.PATIENT_ID = P.ID AND VP.VISIT_ID = V.ID AND VP.DIAGNOSIS_ID = DI.ID
AND DI.NAME IN('CANCER')
GROUP BY D.TITLE
HAVING COUNT(VP.ID) >= 2;

--2--
-- SELECT TOTAL SERVICE COST IN MARCH 2020
SELECT SUM(S.UNIT_PRICE*S.QUANTITY) MARCH_2020_COST
FROM VISIT_PROCESS VP,SERVICE S
WHERE VP.SERVICE_ID = S.ID AND
      VP.PROCESS_DATE BETWEEN '01/03/2020' AND '01/04/2020';


-- 1 SELECT statement with subquery
-- FIND DOCTORS WHO HAVE MAXIMUM SALARY IN EACH TITLE AND 
-- SHOW THEM WITH ADDITIONAL COLUMN AND PUT '*' SIGN, OTERWISE ' '
SELECT NAME, SURNAME, TITLE, SALARY, '*' MAX_IN_TITLE
FROM DOCTOR
WHERE (SALARY,TITLE) IN (SELECT MAX(SALARY), TITLE
                         FROM DOCTOR
                         GROUP BY TITLE)
UNION                    
SELECT NAME, SURNAME, TITLE, SALARY, ' ' MAX_IN_TITLE
FROM DOCTOR
WHERE (SALARY,TITLE) NOT IN (SELECT MAX(SALARY), TITLE
                             FROM DOCTOR
                             GROUP BY TITLE);


-- 1 SELECT statement with correlated subquery
-- FIND ALL DIAGNOSES ABOUT YOUNGEST PATIENTS LIVING IN ISTANBUL FOR EVERY INSURANCE TYPE
SELECT DISTINCT(DI.NAME) DIAGNOSIS_NAME, PA.NAME PATIENT_NAME, PA.SURNAME PATIENT_SURNAME, PA.BIRTHDATE,PA.INSURANCE_ID
FROM DIAGNOSIS DI, VISIT_PROCESS VP, VISIT V, PATIENT PA
WHERE VP.VISIT_ID = V.ID AND VP.DIAGNOSIS_ID = DI.ID AND V.PATIENT_ID = PA.ID
AND PA.ID IN (SELECT P.ID
              FROM PATIENT P
              WHERE P.BIRTHDATE = (SELECT MAX(BIRTHDATE)
                                    FROM PATIENT
                                    WHERE PATIENT.INSURANCE_ID = P.INSURANCE_ID AND PATIENT.GENDER IN('FEMALE')));